name: Blank Issue
description: Create a blank issue.

body:
    - type: markdown
      attributes:
          value: |
              ## Do not use this template to request a plugin to get added to Vencord+, report a bug/crash or request a plugin to get updated.

    - type: textarea
      id: content
      attributes:
          label: Content
      validations:
          required: true
